// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKkGfQBl9rox0pVOG4Am5me2VQ287mGt8',
    appId: '1:620169373797:web:ded65a7b82d7025b9dfe8c',
    messagingSenderId: '620169373797',
    projectId: 'aplication-jasa-jahit',
    authDomain: 'aplication-jasa-jahit.firebaseapp.com',
    storageBucket: 'aplication-jasa-jahit.firebasestorage.app',
    measurementId: 'G-R6QPGZKMWF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdnaGMEiKgvNt0QciVKluLLKYVK4cOIV0',
    appId: '1:620169373797:android:0c14f7dacc1886d59dfe8c',
    messagingSenderId: '620169373797',
    projectId: 'aplication-jasa-jahit',
    storageBucket: 'aplication-jasa-jahit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY9aOGfpMV6zk_wugdq772QA8tTuJj9nk',
    appId: '1:620169373797:ios:65167b2cbd87587d9dfe8c',
    messagingSenderId: '620169373797',
    projectId: 'aplication-jasa-jahit',
    storageBucket: 'aplication-jasa-jahit.firebasestorage.app',
    iosBundleId: 'com.example.jasaJahitAplication',
  );
}
